# Generated by CMake

if("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.8)
   message(FATAL_ERROR "CMake >= 2.8.0 required")
endif()
if(CMAKE_VERSION VERSION_LESS "2.8.3")
   message(FATAL_ERROR "CMake >= 2.8.3 required")
endif()
cmake_policy(PUSH)
cmake_policy(VERSION 2.8.3...3.24)
#----------------------------------------------------------------
# Generated CMake target import file.
#----------------------------------------------------------------

# Commands may need to know the format version.
set(CMAKE_IMPORT_FILE_VERSION 1)

# Protect against multiple inclusion, which would fail when already imported targets are added once more.
set(_cmake_targets_defined "")
set(_cmake_targets_not_defined "")
set(_cmake_expected_targets "")
foreach(_cmake_expected_target IN ITEMS MUMPS::MPISEQ MUMPS::mpiseq_c MUMPS::mpiseq_fortran MUMPS::PORD MUMPS::COMMON MUMPS::SMUMPS MUMPS::DMUMPS MUMPS::CMUMPS MUMPS::ZMUMPS MUMPS::MUMPS)
  list(APPEND _cmake_expected_targets "${_cmake_expected_target}")
  if(TARGET "${_cmake_expected_target}")
    list(APPEND _cmake_targets_defined "${_cmake_expected_target}")
  else()
    list(APPEND _cmake_targets_not_defined "${_cmake_expected_target}")
  endif()
endforeach()
unset(_cmake_expected_target)
if(_cmake_targets_defined STREQUAL _cmake_expected_targets)
  unset(_cmake_targets_defined)
  unset(_cmake_targets_not_defined)
  unset(_cmake_expected_targets)
  unset(CMAKE_IMPORT_FILE_VERSION)
  cmake_policy(POP)
  return()
endif()
if(NOT _cmake_targets_defined STREQUAL "")
  string(REPLACE ";" ", " _cmake_targets_defined_text "${_cmake_targets_defined}")
  string(REPLACE ";" ", " _cmake_targets_not_defined_text "${_cmake_targets_not_defined}")
  message(FATAL_ERROR "Some (but not all) targets in this export set were already defined.\nTargets Defined: ${_cmake_targets_defined_text}\nTargets not yet defined: ${_cmake_targets_not_defined_text}\n")
endif()
unset(_cmake_targets_defined)
unset(_cmake_targets_not_defined)
unset(_cmake_expected_targets)


# Compute the installation prefix relative to this file.
get_filename_component(_IMPORT_PREFIX "${CMAKE_CURRENT_LIST_FILE}" PATH)
get_filename_component(_IMPORT_PREFIX "${_IMPORT_PREFIX}" PATH)
if(_IMPORT_PREFIX STREQUAL "/")
  set(_IMPORT_PREFIX "")
endif()

# Create imported target MUMPS::MPISEQ
add_library(MUMPS::MPISEQ STATIC IMPORTED)

set_target_properties(MUMPS::MPISEQ PROPERTIES
  INTERFACE_LINK_LIBRARIES "MUMPS::mpiseq_fortran;MUMPS::mpiseq_c"
)

# Create imported target MUMPS::mpiseq_c
add_library(MUMPS::mpiseq_c STATIC IMPORTED)

set_target_properties(MUMPS::mpiseq_c PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include"
)

# Create imported target MUMPS::mpiseq_fortran
add_library(MUMPS::mpiseq_fortran STATIC IMPORTED)

set_target_properties(MUMPS::mpiseq_fortran PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include"
  INTERFACE_LINK_LIBRARIES "MUMPS::mpiseq_c"
)

# Create imported target MUMPS::PORD
add_library(MUMPS::PORD STATIC IMPORTED)

set_target_properties(MUMPS::PORD PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include"
)

# Create imported target MUMPS::COMMON
add_library(MUMPS::COMMON STATIC IMPORTED)

set_target_properties(MUMPS::COMMON PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include"
  INTERFACE_LINK_LIBRARIES "\$<\$<BOOL:OFF>:PARMETIS::PARMETIS>;\$<\$<BOOL:OFF>:METIS::METIS>;MUMPS::PORD;\$<\$<AND:\$<BOOL:ON>,\$<BOOL:OFF>>:SCALAPACK::SCALAPACK>;LAPACK::LAPACK;\$<\$<BOOL:OFF>:CUDA::cublas;CUDA::cudart>;\$<\$<BOOL:>:>;\$<LINK_ONLY:MUMPS::mpiseq_fortran>;\$<LINK_ONLY:MUMPS::mpiseq_c>;\$<LINK_ONLY:\$<\$<BOOL:OFF>:OpenMP::OpenMP_Fortran;OpenMP::OpenMP_C>>"
)

# Create imported target MUMPS::SMUMPS
add_library(MUMPS::SMUMPS STATIC IMPORTED)

set_target_properties(MUMPS::SMUMPS PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include"
  INTERFACE_LINK_LIBRARIES "MUMPS::COMMON;\$<LINK_ONLY:MUMPS::mpiseq_fortran>;\$<LINK_ONLY:\$<\$<BOOL:OFF>:OpenMP::OpenMP_Fortran>>"
)

# Create imported target MUMPS::DMUMPS
add_library(MUMPS::DMUMPS STATIC IMPORTED)

set_target_properties(MUMPS::DMUMPS PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include"
  INTERFACE_LINK_LIBRARIES "MUMPS::COMMON;\$<LINK_ONLY:MUMPS::mpiseq_fortran>;\$<LINK_ONLY:\$<\$<BOOL:OFF>:OpenMP::OpenMP_Fortran>>"
)

# Create imported target MUMPS::CMUMPS
add_library(MUMPS::CMUMPS STATIC IMPORTED)

set_target_properties(MUMPS::CMUMPS PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include"
  INTERFACE_LINK_LIBRARIES "MUMPS::COMMON;\$<LINK_ONLY:MUMPS::mpiseq_fortran>;\$<LINK_ONLY:\$<\$<BOOL:OFF>:OpenMP::OpenMP_Fortran>>"
)

# Create imported target MUMPS::ZMUMPS
add_library(MUMPS::ZMUMPS STATIC IMPORTED)

set_target_properties(MUMPS::ZMUMPS PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include"
  INTERFACE_LINK_LIBRARIES "MUMPS::COMMON;\$<LINK_ONLY:MUMPS::mpiseq_fortran>;\$<LINK_ONLY:\$<\$<BOOL:OFF>:OpenMP::OpenMP_Fortran>>"
)

# Create imported target MUMPS::MUMPS
add_library(MUMPS::MUMPS INTERFACE IMPORTED)

set_target_properties(MUMPS::MUMPS PROPERTIES
  INTERFACE_LINK_LIBRARIES "MUMPS::SMUMPS;MUMPS::DMUMPS;MUMPS::CMUMPS;MUMPS::ZMUMPS"
)

if(CMAKE_VERSION VERSION_LESS 3.0.0)
  message(FATAL_ERROR "This file relies on consumers using CMake 3.0.0 or greater.")
endif()

# Load information for each installed configuration.
file(GLOB _cmake_config_files "${CMAKE_CURRENT_LIST_DIR}/MUMPS-targets-*.cmake")
foreach(_cmake_config_file IN LISTS _cmake_config_files)
  include("${_cmake_config_file}")
endforeach()
unset(_cmake_config_file)
unset(_cmake_config_files)

# Cleanup temporary variables.
set(_IMPORT_PREFIX)

# Loop over all imported files and verify that they actually exist
foreach(_cmake_target IN LISTS _cmake_import_check_targets)
  foreach(_cmake_file IN LISTS "_cmake_import_check_files_for_${_cmake_target}")
    if(NOT EXISTS "${_cmake_file}")
      message(FATAL_ERROR "The imported target \"${_cmake_target}\" references the file
   \"${_cmake_file}\"
but this file does not exist.  Possible reasons include:
* The file was deleted, renamed, or moved to another location.
* An install or uninstall procedure did not complete successfully.
* The installation package was faulty and contained
   \"${CMAKE_CURRENT_LIST_FILE}\"
but not all the files it references.
")
    endif()
  endforeach()
  unset(_cmake_file)
  unset("_cmake_import_check_files_for_${_cmake_target}")
endforeach()
unset(_cmake_target)
unset(_cmake_import_check_targets)

# This file does not depend on other imported targets which have
# been exported from the same project but in a separate export set.

# Commands beyond this point should not need to know the version.
set(CMAKE_IMPORT_FILE_VERSION)
cmake_policy(POP)
